### PR TITLE
Trainer: add Dynamic Difficulty Slider

### PR DESCRIPTION
**Pull request by pas-de-2**
Currently works in normal mode and Separate Ways. Doesn't work in Assignment Ada, Mercs mode, or professional.

Like I said in the PR thread, the modes with fixed difficulties instantly reset `dynamicDifficultyPoints` whenever you attempt to modify it. Updating the value via `Trainer_Update()` manages to give the superficial impression that the difficulty is being overriden in the globals panel, but the game's logic is still updating according to the internal difficulty setting. You can test this by starting up Assignment Ada, setting the difficulty override to 1, and seeing how much damage you take vs how much damage you take with the `SYS_OMAKE_ADA_GAME` flag disabled (this disables the internal override).

Additionally, professional mode sets `dynamicDifficultyLevel` directly to 10, which is a redundancy to keep in mind. This is all handled in the `GameAddPoint` function of bio4-110.c:. For example, this is what sets Assignment Ada's `dynamicDifficultyPoints` to 4500, or 6500 if you're in room 40E (Krauser boss fight):
```cpp
if ( (v8->Flags_SYSTEM_0_54[0] & 0x80000000) != 0 )
  {
    if ( pSys->language_8 == 1 || (v8->dynamicDifficultyPoints_4F94 = 0x1194, v8 = pG, pG->curRoomId_4FAC == 0x40E) )
    {
      v8->dynamicDifficultyPoints_4F94 = 0x1964;
      v8 = pG;
    }
  }
```

It would be good if you could work your magic to help finish this, or point me to a resource to get started with finding addresses and injecting.

### CODE REVIEW

**Comment by emoose** [comment]
>point me to a resource to get started with finding addresses and injecting.

Ideally you'd use IDA 7.7 with our database to find the code for it, how I'd do it is look at the
`if ( (v8->Flags_SYSTEM_0_54[0] & 0x80000000) != 0 )`
line in the hex-rays decompilation, then jump to the assembly from that line, which would put you roughly where that check happens in the disassembly, at around ~0x63B199:
image
(might need the https://github.com/REhints/HexRaysCodeXplorer plugin to allow jumping from the decompilation -> assembly)

Then from that assembly, work out what I'd want to patch (I guess here one way could be to patch the `jz` to `jmp` instead, so that it'd pretty much always skip the code that overwrites the difficulty), figure out a pattern from the surrounding instructions that lets us find that code across all the EXEs, and then add code to patch that jmp in.

For patterns I usually just copy a few bytes around the instruction I'm looking for, but make sure to change any `jmp/jz/etc` or any other instruction that uses a memory address to use ? wildcard instead, since those probably use different addrs on other versions - though including offsets like the +4F94 / +4FAC in the listing above is usually fine (fortunately they didn't really change the struct layouts much between the versions), might make it easier to find a unique pattern too.

If we want to let the option be toggled during gameplay we'd need to do it a bit differently though, one way could be to patch/unpatch the jmp whenever `bTrainerOverrideDynamicDifficulty` is changed, but I don't think we really have much setup to handle patching when a setting changes (but could be wrong about that...)

Another way would be to add an inline hook there which would check against `bTrainerOverrideDynamicDifficulty`, those hooks need 6 bytes to work, the first `test dword ptr ....` line there would probably be perfect (that instruction is more than 6 bytes, but MakeInline can fill that with nops), that's usually how we handle runtime stuff like this, maybe more stable than trying to patch bytes during gameplay.

Inside that inline hook you could just update the eflags zero-flag, which would then affect the `jz` in the listing above, either making it skip the jump (letting it run the code that overwrites difficulty), or to follow it (leaving the difficulty untouched), the `UnlockAshleyJPCameraAngles` hook might be a good example of how that works: https://github.com/nipkownix/re4_tweaks/blob/d649a98bbdc60f705d88d90fd6de8ae05c2af1b2/dllmain/Misc.cpp#L1050
(that hook is replacing the mov/cmp at 0x6F5518 if you want to look into it)

Since the `test dword ptr ...` was replaced to make the hook you'd need to reimplement what that did too, by checking for the SYS_OMAKE_ADA_GAME / 0x80000000 flag and updating the zero-flag like it would have.

I guess one way that hook could be setup would be like:
```C
bool letGameOverrideAdaDifficulty = FlagIsSet(GlobalPtr()->Flags_SYSTEM_0_54, uint32_t(Flags_SYSTEM::SYS_OMAKE_ADA_GAME)); // same as the test dword ptr ...
if (pConfig->bTrainerOverrideDynamicDifficulty)
  letGameOverrideAdaDifficulty = false;

if (letGameOverrideAdaDifficulty)
  regs.ef |= (1 << regs.zero_flag);
else
  regs.ef &= ~(1 << regs.zero_flag);
```

You might be able to use Ghidra instead of IDA, but I'm not sure if that might require IDA to convert the database over first... if it does maybe I'll have to start adding pre-converted Ghidra DBs with it too.

One other way I can think of is to use Cheat Engine, that has a disassembler built in which can load in our PDB file (once [relocations have been disabled](https://github.com/nipkownix/re4_tweaks/issues/201#issuecomment-1150146256) on the EXE), with that loaded you can jump to functions by name, it's pretty useful for testing out instruction patches, could probably figure out hooks/patterns from it too.

Hope this helps some, if you need me to go into anything more here let me know!

(E: maybe Ghidra would be able to load in the PDB too, might also need the relocations thing though, that should give it names for funcs & vars at least, but don't think the PDB has structs included unfortunately)

(E2: oh just realised, could maybe handle updating the `dynamicDifficultyPoints_4F94` value inside that hook too, rather than updating inside `Trainer_Update` every frame, that way difficulty code can stay closer together, and I guess would also let it only write to the difficulty addr when it's actually being used by GameAddPoint too - not sure if there's any other code besides GameAddPoint that uses that Points_4F94 field though, if there are other things using it maybe keeping it in Trainer_Update would be best...)

**Comment by pas-de-2** [comment]
The only other place where the game modifies `dynamicDifficultyPoints_4F94` without immediately calling GameAddPoint is GamePointBossReset, which looks like it sets a minimum difficulty of 5500 for boss encounters if you haven't pressed continue. We could just add another inline hook to skip this?

Anyways, I should have a copy of IDA soon. I really appreciate all the effort you've put into giving me a crash course on this.

**Comment by pas-de-2** [comment]
Hey it seems to work, though it's not loading the symbol names when generating pseudocode. Did I miss an option? I can still figure out what's what from bio4-110.c at least.

I looked at HexRaysCodeXplorer and I don't think I can build the plugin for IDA 7.x without the IDA SDK. I can workaround this with 'synchronize with Hex View' at least. Maybe you could upload your .dll somewhere?

**Comment by emoose** [comment]
About the `GamePointBossReset` use, seems like it's only really setting the Points_4F value there and not actually using it for anything, so hopefully `GameAddPoint` hook would still be able to override it (it does seem to write something to savegame in that bossreset func though, but keeping the difficulty override working across saves probably isn't that important)

(that's assuming that nothing else besides GameAddPoint actually uses Points_4F, and AddPoint is just calculating `dynamicDifficultyLevel_4F98` which other code does use, could be wrong about it tho - but if this is how it works, maybe we'd also need to call AddPoint whenever player changes the difficulty to make sure Level gets updated...)

E: also GameAddPoint does seem to have a bunch of other checks that can change the Points value too, like for SYS_HARD_MODE flag etc, maybe adding the hook that overrides it somewhere later in that func after all those checks would be better, right before where it calcs the DifficultyLevel maybe, might not have to deal with the `jz` stuff that way too.

E2: also if you want IDA to show the bytes next to disassembly, go to Options -> General and set "number of opcode bytes" to 10, you could also turn on auto comments there too which gives you an idea of what each asm instruction does.

**Comment by pas-de-2** [comment]
Looks like I got the slider working everywhere now. I wound up inserting a hook like you suggested at the final DifficultyLevel assignment. Only problem is that there's an early return in the prior switch statement if you're playing on Professional, so I added a second hook to deal with that case.

Oh and you're right about `GamePointBossRight`, GameAddPoint gets called every frame regardless of mode, so there's no need to worry about it.

Let me know how it looks, this was fun. I'm learning a lot about low level stuff I never paid much attention to before.

**Comment by emoose** [comment]
The code seems good, but pro mode stuff might need a little work, VS debugger gave me an exception at
>__asm {movzx eax, byte ptr[ecx + 0x847C]}

Seems ecx was set to 0x246 there for some reason, changing that to `regs.eax = *(uint8_t*)(regs.ecx + 0x847C);` seemed to get rid of it though.
Unfortunately doesn't look like the override is getting set on pro mode though, globals viewer still shows it as level = 10 no matter what level I override to, looks like it does get applied fine on normal-mode saves though.

It might be the `dec eax` that comes after where you hooked, think that might be able to update eflags, maybe setting `regs.eax` to some certain value can let it take the branch you wanted.

E: this seems to work for me:
```C
		struct ProfessionalModeOverride
		{
			void operator()(injector::reg_pack& regs)
			{
				if (pConfig->bTrainerOverrideDynamicDifficulty)
					regs.eax = uint32_t(GameDifficulty::VeryEasy); // exit switch through VERYEASY case
				else
					regs.eax = *(uint8_t*)(regs.ecx + 0x847C); // orig code we overwrote
			}
		};
```

E: the weird `0x10624DD3i64 * GlobalPtr()->dynamicDifficultyPoints_4F94 >> 0x20)) >> 6;` stuff seems to be some compiler optimization they used, looks like PS2 & RE4VR have the actual calc for those.
Seems the `0x10624DD3i64` stuff is just `points / 1000`, `0x5F533929i64` is `points / 2750`, and `0x4777C3B3i64` is `points / 1834`, unless they changed something about it in the VR port at least.

**Comment by pas-de-2** [comment]
Ok, updated 👍

Still trying to wrap my head around the type pruning. I'm guessing that we aren't supposed to type cast `edx` judging by code used elsewhere, but I'm not sure why.

**Comment by emoose** [comment]
Looks good, pro seems to work fine now, tested with all the builds we support and all seemed to work fine too.

I did get one weird crash with JPN build though, haven't been able to reproduce it so not sure if it's actually caused by this or not... Here's crash log for that: 
[bio4.exe.20221110224805a.zip](https://github.com/emoose/re4_tweaks/files/9985152/bio4.exe.20221110224805a.zip)
That happened when I loaded into the save at slot 18, I toggled the difficulty setting almost immediately after loading in, and then got a crash error message almost as soon as I enabled it, weird thing is that game was still running in background behind the msg though, guess it was just some unimportant thread that crashed.

Will try taking a look into it soon, don't really think it's related to the difficulty stuff though seeing as I couldn't repro it.
I don't have any IDB for the JP build unfortunately, but you can use patches at https://github.com/emoose/re4-research/issues/5 to get the EXE and then load it into IDA.

E: ah looks like that crash was in audio related code, so probably not related then.

I was also thinking that it'd be nice if we could have some kind of "freeze difficulty level" toggle that would just stop dynamic difficulty being changed too, I guess for that we'd just need `GameAddPoint` to be skipped when called, could probably be done by hooking `j_GameAddPoint` to jump to our own func and then decide whether to call `GameAddPoint` or not (maybe would also need that BossReset func to be hooked as well though)

That also made me realize we could probably handle the difficulty level/points override inside the same kind of hook as well, just update it after GameAddPoint has been ran (or skip calling that and just set it directly), rather than needing to inline hook GameAddPoint itself...

I think this is fine to merge already, but might try looking into the above later on, any thoughts would be welcomed though.

E: alternatively we could maybe just let `iTrainerDynamicDifficultyLevel` get updated to match the games current difficulty level whenever the override isn't enabled, then to freeze it the user can just enable the override - would lose their current points value though, but that's only minor, would save us needing to hook a bunch of extra things...

**Comment by pas-de-2** [comment]
Oh that's a much nicer method! Everything seems to be working. I tried using the xdelta patches to generate some other exes for testing, but 110-to-106.xdelta is giving me `target window checksum mismatch`.

You know, I originally set `pConfig->iTrainerDynamicDifficultyLevel = GlobalPtr()->dynamicDifficultyLevel_4F98;` in ImGui so the slider was always equal to the current difficulty level. Dunno why I got rid of that, but it's a good idea.

**Comment by emoose** [comment]
Good stuff, thanks for updating it! Did you use the xdelta with the orig 110 exe? If you patched the EXE for 4GB or relocations it might not work.

About the call conventions, cdecl should be right for that I think, fastcall is only really needed when you're hooking/calling class functions (kinda lets you emulate __thiscall which VC doesn't normally let you use)
If you see stdcall anywhere that's usually a mistake, don't think game actually uses that for anything (accidentally had that set as IDA's default early on though, so it might show up in a few places)

IDA also tends to turn class functions into stdcall if the function doesn't actually make use of `this` too, those do still get called with `this` inside ecx though, so I try fixing those to __thiscall in the IDB when I spot them.

**Comment by pas-de-2** [comment]
>If you patched the EXE for 4GB or relocations it might not work.

Aha, that was it, forgot about that.

**Pull request merged**
